### ISSUE TITLE
The download link is for viewing only, not downloading

### ISSUE THREAD

**Issue by 464hee** [owkin/HistoSSLscaling#1]
![image](https://github.com/owkin/HistoSSLscaling/assets/100740023/5ed289eb-614e-4a57-9bd8-328cae85edd6)

**Comment by 464hee** [comment]
@afilt

**Comment by afilt** [comment]
Updated it. Can you download the data now ?

**Comment by 464hee** [comment]
No,. You should send me the new download link. @afilt

**Comment by 464hee** [comment]
The link I've viewed so far is https://drive.google.com/drive/folders/16XtgLTFUxB_sZ9rRlYINinIbJeiTdFz9?usp=sharing, still in view-only not downloadable status

**Comment by lysukhin** [comment]
Hello @afilt !
I think the [link in README](https://drive.google.com/drive/folders/16XtgLTFUxB_sZ9rRlYINinIbJeiTdFz9) is still not working for data downloading. Could you please update or fix it somehow?
Thanks in advance.

**Comment by afilt** [comment]
Hi @lysukhin, should be good now.

**Comment by lysukhin** [comment]
@afilt it actually is, thanks a lot!
