### ISSUE TITLE
the colab notebook can't open

### ISSUE THREAD

**Issue by yangzhou321** [owkin/HistoSSLscaling#10]
Hi! Thank you for your impressive work! But I got a problem when opening the recent shared [colab notebook](https://colab.research.google.com/drive/1zjxscEBgpizHBCwMy-aNz2916AVdB642). Could you please open the download permission of it? Thanks a lot!

**Comment by afilt** [comment]
Hi @yangzhou321. This should be good now, can you confirm ?

**Comment by yangzhou321** [comment]
Yes! Everything is ok! Thank you a lot for sharing this  impressive work!
