### ISSUE TITLE
How to access "owkin/phikon" Hugginface model?

### ISSUE THREAD

**Issue by sergiosstbn** [owkin/HistoSSLscaling#14]
Thanks for the awesome work!

I am trying to follow the tutorial (https://github.com/owkin/HistoSSLscaling/blob/main/notebooks/phikon_tutorial.ipynb) and it fails to find the model "owkin/phikon" on the Hugginface hub, even after being authenticated with a Hugginface access token.

Should I request access in another way?

**Comment by afilt** [comment]
Hello @sergiosstbn, should be good now :)

**Comment by sergiosstbn** [comment]
Hello @afilt, yes, now it's working. Thank you for resolving this so quickly!
