### ISSUE TITLE
Unrecognised keys in ibot_vit_base_pancan.pth

### ISSUE THREAD

**Issue by VolodymyrChapman** [owkin/HistoSSLscaling#17]
Hi there,

## Brief issue description:
Weights file ibot_vit_base_pancan.pth from Google Drive, downloaded on 10th January 2024 have unrecognised keys when attempting inference.

## Error message:
INFO     | rl_benchmarks.models.feature_extractors.ibot_vit:__init__:78 - Pretrained weights found at /storage_mount/from_analyses/2024_01_Phikon/ibot_vit_base_pancan.pth and loaded with msg: _IncompatibleKeys(missing_keys=[], unexpected_keys=['head.mlp.0.weight', 'head.mlp.0.bias', 'head.mlp.2.weight', 'head.mlp.2.bias', 'head.mlp.4.weight', 'head.mlp.4.bias', 'head.last_layer.weight_g', 'head.last_layer.weight_v', 'head.last_layer2.weight_g', 'head.last_layer2.weight_v'])

## Steps to reproduce error:
1) Download ibot_vit_base_pancan.pth weights from Google Drive from the link: https://github.com/owkin/HistoSSLscaling#download 
2) Follow installation instructions  as outlined in https://github.com/owkin/HistoSSLscaling#installing-rl_benchmarks-package-within-this-repo 
3) Attempt inference, as per instructions at the top of README.md (note, I have used my own ):
```
# feature extraction snippet with `rl_benchmarks` repository
from PIL import Image
from rl_benchmarks.models import iBOTViT

# instantiate iBOT ViT-B Pancancer model, aka Phikon
# /!\ please use the "teacher" encoder which produces better results !
weights_path =  '/storage_mount/from_analyses/2024_01_Phikon/ibot_vit_base_pancan.pth' 
ibot_base_pancancer = iBOTViT(architecture="vit_base_pancan", encoder="teacher", weights_path=weights_path)

# load an image and transform it into a normalized tensor
image = Image.open("assets/example.tif")  # (224, 224, 3), uint8
tensor = ibot_base_pancancer.transform(image) # (3, 224, 224), torch.float32
batch = tensor.unsqueeze(0)  # (1, 3, 224, 224), torch.float32

# compute the 768-d features
features = ibot_base_pancancer(batch).detach().cpu().numpy()
assert features.shape == (1, 768)
```
## Hardware / software details:
* OS: Ubuntu 22.04
* NVIDIA driver version: 545.29.06
* All libraries and environment variables as created in fresh conda env following the installation instructions:
`python -m pip install -e .  -r requirements.txt `

Than you in advance for your support and kudos on the awesome work, Owkin!

**Comment by jbschiratti** [comment]
That's just a warning from pytorch (and also, there are no keys are missing from the checkpoint). The head's weights are included in the checkpoint. That's why pytorch complains. You can use the model anyway.

**Comment by VolodymyrChapman** [comment]
Thank you for the quick response and for clarifying.
Good to have the peace of mind that it's behaving as expected.
Best wishes, V
